// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgsbooeytnvbbgspvpmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnc2Jvb2V5dG52YmJnc3B2cG1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NjM0OTEsImV4cCI6MjA3MTIzOTQ5MX0.RjV1A6NgdbIUqTEnbPh3lpYQBZswJ1C6lt1BPCaQpG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});